baseURL: https://nt.web.ve/
permalinks:
  blog: /:sections/:slug/
  gallery: /:sections/:slug/
  projects: /:sections/:slug/
taxonomies:
  tag: tags
  serie: series
Paginate: 10
enableEmoji: true
markup:
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    tabWidth: 2
  tableOfContents:
    startLevel: 1
    endLevel: 6
  goldmark:
    renderer:
      unsafe: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
    - JSON
  taxonomyTerm:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - JSON
enableRobotsTXT: true
params:
  name: ntrrg
  title: ntrrg
  titleSeparator: "-"
  author: ntrrg
  singleAuthor: true
  image: /images/logo-bg.png
  ampImage: /images/isologo-amp.png
  cookiesAlert: true
  # googleTagManager: GTM-NZ2R3W7
  disqus: ntweb
  goPlayground: https://play.golang.org
  projects:
    - https://github.com/ntrrg/docker-hugo
    - https://github.com/ntrrg/pish
    - https://github.com/ntrrg/ntgo
    - https://github.com/ntrrg/sdb
  secundaryMenu:
    items:
      - url: "/settings/"
    before: "["
    after: "]"
  footerMenu:
    items:
      - url: "/payments/"
    before: "["
    after: "]"
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: I am Miguel Angel, just another developer working hard to not be just another developer.
      menu:
        items:
          - url: "/challenges/"
          - url: "/projects/"
          - url: "/gallery/"
        before: "| "
  es:
    languageName: Español
    params:
      description: Soy Miguel Angel, solo otro desarrollador más trabajando duro para no ser solo otro desarrollador más.
      menu:
        items:
          - url: "/blog/"
          - url: "/projects/"
          - url: "/gallery/"
        before: "| "

