#!/bin/sh

set -e

OUTPUT="output/mage-$(go env GOOS)-$(go env GOARCH)$(go env GOARM)"

cd ".mage"

FILES="$(go list -tags mage -f '{{ .GoFiles }}' | tr -d '[]')"

for FILE in $FILES; do
  if [ ! -x "$OUTPUT" ] || [ "$FILE" -nt "$OUTPUT" ]; then
    GOFLAGS="-mod=vendor" mage -compile "$OUTPUT"
    break
  fi
done

cd ..
exec ".mage/$OUTPUT" "$@"

