#!/bin/sh

set -e

OUTPUT="output/mage-$(go env GOOS)-$(go env GOARCH)"

cd ".mage"

if [ "magefile.go" -nt "$OUTPUT" ]; then
  go run "mage.go" -compile "$OUTPUT"
fi

cd ..
exec ".mage/$OUTPUT" "$@"

